name: enclosedbot
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  http: ^1.5.0
  teledart: ^0.6.1
  drift: ^2.28.1
  sqlite3: ^2.9.0
  path: ^1.9.1
  image: ^4.5.4
  lints: ^6.0.0
  l: ^5.0.1

dev_dependencies:
  drift_dev: ^2.28.1
  build_runner: ^2.6.1
